/*
 * This file is part of the Meteor Seed Explorer Addon distribution (https://github.com/SeedExplorer/meteor-seed-explorer).
 * Copyright (c) SeedExplorer Team.
 */

package me.seedexplorer.addon.gui;

import me.seedexplorer.addon.map.BiomeGenerator;
import me.seedexplorer.addon.map.ChunkTile;
import me.seedexplorer.addon.map.MinimapManager;
import me.seedexplorer.addon.modules.SeedExplorerModule;
import me.seedexplorer.addon.ore.OreCache;
import me.seedexplorer.addon.ore.OrePatch;
import me.seedexplorer.addon.structures.GeneratedStructure;
import me.seedexplorer.addon.structures.StructureCache;
import me.seedexplorer.addon.structures.StructurePredictor;
import me.seedexplorer.addon.structures.StructureType;
import me.seedexplorer.addon.waypoints.SeedWaypoint;
import me.seedexplorer.addon.waypoints.WaypointManager;
import me.seedexplorer.addon.seed.SeedManager;
import meteordevelopment.meteorclient.gui.GuiTheme;
import meteordevelopment.meteorclient.gui.WidgetScreen;
import meteordevelopment.meteorclient.gui.renderer.GuiRenderer;
import meteordevelopment.meteorclient.gui.widgets.input.WTextBox;
import meteordevelopment.meteorclient.renderer.Renderer2D;
import meteordevelopment.meteorclient.systems.modules.Modules;
import meteordevelopment.meteorclient.utils.player.ChatUtils;
import meteordevelopment.meteorclient.utils.render.color.Color;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.util.Mth;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Fullscreen infinite map screen for seed exploration.
 * Supports panning with left-click drag and zooming with scroll wheel.
 * Renders chunk tiles generated by MinimapManager using BiomeGenerator.
 * Renders predicted structure icons as a layer on top of the biome map.
 * Renders existing seed waypoints as distinct markers.
 * Provides hover tooltips and right-click context menu for structures and waypoints.
 */
public class SeedExplorerScreen extends WidgetScreen {
    private double offsetX, offsetZ;
    private double zoom = 1.0;

    private boolean dragging;
    private double dragStartX, dragStartY;
    private double dragOffsetX, dragOffsetZ;

    // Dimension selector
    private int selectedDimension = 0; // 0=Overworld, -1=Nether, 1=End

    // Structure data
    private List<GeneratedStructure> visibleStructures = new ArrayList<>();
    private GeneratedStructure hoveredStructure;
    private GeneratedStructure selectedStructure;

    // Waypoint data
    private List<SeedWaypoint> visibleWaypoints = new ArrayList<>();
    private SeedWaypoint hoveredWaypoint;
    private SeedWaypoint selectedWaypoint;

    // Ore data
    private List<OrePatch> visibleOres = new ArrayList<>();

    // Context menu
    private boolean contextMenuOpen;
    private double contextMenuX, contextMenuY;
    private boolean isWaypointContextMenu; // true if context menu is for a waypoint, false for structure

    // Search bar
    private WTextBox searchBar;

    // Biome name to ID mapping for search
    private static final Map<String, Integer> BIOME_NAME_TO_ID = new HashMap<>();
    static {
        BIOME_NAME_TO_ID.put("ocean", 0);
        BIOME_NAME_TO_ID.put("deep ocean", 1);
        BIOME_NAME_TO_ID.put("warm ocean", 2);
        BIOME_NAME_TO_ID.put("lukewarm ocean", 3);
        BIOME_NAME_TO_ID.put("cold ocean", 4);
        BIOME_NAME_TO_ID.put("deep lukewarm ocean", 5);
        BIOME_NAME_TO_ID.put("deep cold ocean", 6);
        BIOME_NAME_TO_ID.put("deep frozen ocean", 7);
        BIOME_NAME_TO_ID.put("plains", 8);
        BIOME_NAME_TO_ID.put("sunflower plains", 9);
        BIOME_NAME_TO_ID.put("forest", 10);
        BIOME_NAME_TO_ID.put("dark forest", 11);
        BIOME_NAME_TO_ID.put("birch forest", 12);
        BIOME_NAME_TO_ID.put("old growth birch forest", 13);
        BIOME_NAME_TO_ID.put("taiga", 14);
        BIOME_NAME_TO_ID.put("old growth taiga", 15);
        BIOME_NAME_TO_ID.put("snowy taiga", 16);
        BIOME_NAME_TO_ID.put("snowy plains", 17);
        BIOME_NAME_TO_ID.put("snowy slopes", 18);
        BIOME_NAME_TO_ID.put("ice spikes", 19);
        BIOME_NAME_TO_ID.put("savanna", 20);
        BIOME_NAME_TO_ID.put("savanna plateau", 21);
        BIOME_NAME_TO_ID.put("desert", 22);
        BIOME_NAME_TO_ID.put("badlands", 23);
        BIOME_NAME_TO_ID.put("windswept hills", 24);
        BIOME_NAME_TO_ID.put("windswept gravelly hills", 25);
        BIOME_NAME_TO_ID.put("windswept forest", 26);
        BIOME_NAME_TO_ID.put("stony peaks", 27);
        BIOME_NAME_TO_ID.put("meadow", 28);
        BIOME_NAME_TO_ID.put("jungle", 29);
        BIOME_NAME_TO_ID.put("sparse jungle", 30);
        BIOME_NAME_TO_ID.put("bamboo jungle", 31);
        BIOME_NAME_TO_ID.put("swamp", 32);
        BIOME_NAME_TO_ID.put("beach", 33);
        BIOME_NAME_TO_ID.put("river", 34);
        BIOME_NAME_TO_ID.put("mushroom fields", 35);
        BIOME_NAME_TO_ID.put("nether wastes", 36);
        BIOME_NAME_TO_ID.put("crimson forest", 37);
        BIOME_NAME_TO_ID.put("warped forest", 38);
        BIOME_NAME_TO_ID.put("soul sand valley", 39);
        BIOME_NAME_TO_ID.put("basalt deltas", 40);
        BIOME_NAME_TO_ID.put("the end", 41);
        BIOME_NAME_TO_ID.put("end midlands", 42);
        BIOME_NAME_TO_ID.put("end barrens", 43);
        BIOME_NAME_TO_ID.put("small end islands", 44);
        BIOME_NAME_TO_ID.put("cherry grove", 45);
        BIOME_NAME_TO_ID.put("pale garden", 46);
        BIOME_NAME_TO_ID.put("frozen ocean", 47);
        BIOME_NAME_TO_ID.put("frozen river", 48);
    }

    // Structure icon colors by type
    private static final Color VILLAGE_COLOR = new Color(180, 60, 60, 220);
    private static final Color DESERT_COLOR = new Color(220, 200, 80, 220);
    private static final Color JUNGLE_COLOR = new Color(60, 200, 60, 220);
    private static final Color WITCH_COLOR = new Color(120, 40, 160, 220);
    private static final Color IGLOO_COLOR = new Color(200, 220, 240, 220);
    private static final Color OUTPOST_COLOR = new Color(120, 120, 120, 220);
    private static final Color MONUMENT_COLOR = new Color(40, 100, 220, 220);
    private static final Color MANSION_COLOR = new Color(160, 80, 40, 220);
    private static final Color ANCIENT_CITY_COLOR = new Color(40, 200, 180, 220);
    private static final Color PORTAL_COLOR = new Color(180, 40, 200, 220);
    private static final Color SHIPWRECK_COLOR = new Color(160, 120, 60, 220);
    private static final Color RUIN_COLOR = new Color(100, 140, 180, 220);
    private static final Color TREASURE_COLOR = new Color(255, 215, 0, 220);
    private static final Color FORTRESS_COLOR = new Color(180, 40, 40, 220);
    private static final Color BASTION_COLOR = new Color(120, 60, 140, 220);
    private static final Color END_CITY_COLOR = new Color(160, 60, 200, 220);

    // Waypoint marker colors
    private static final Color WAYPOINT_MARKER_COLOR = new Color(255, 255, 100, 220);
    private static final Color WAYPOINT_HOVER_COLOR = new Color(255, 255, 180, 255);

    public SeedExplorerScreen(GuiTheme theme) {
        super(theme, "Seed Explorer");
    }

    @Override
    public void initWidgets() {
        searchBar = theme.textBox("", "Search (X Z, structure, biome)...");
        enterAction = this::onSearch;
        add(searchBar).top().right().pad(10).width(250);
    }

    @Override
    protected void onRenderBefore(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
        renderMap(mouseX, mouseY, delta);

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        // Update visible structures based on current viewport
        updateVisibleStructures();
        updateVisibleWaypoints();
        updateVisibleOres();

        // Render structure icons
        renderStructures(mouseX, mouseY);

        // Render ore overlay
        renderOres(mouseX, mouseY);

        // Render seed waypoint markers
        renderWaypoints(mouseX, mouseY);

        // Draw coordinates overlay at bottom-left
        double worldX = offsetX + (mouseX - screenWidth / 2.0) / zoom;
        double worldZ = offsetZ + (mouseY - screenHeight / 2.0) / zoom;
        String coords = String.format("X: %.1f, Z: %.1f (Zoom: %.2f)", worldX, worldZ, zoom);
        theme.textRenderer().begin(1.0);
        theme.textRenderer().render(coords, 10, screenHeight - 20, theme.textColor());
        theme.textRenderer().end();

        // Draw dimension selector at top-left
        drawDimensionSelector();

        // Draw crosshair at center
        double cx = screenWidth / 2.0;
        double cy = screenHeight / 2.0;
        theme.textRenderer().begin(1.0);
        theme.textRenderer().render("+", cx - 3, cy - 4, Color.WHITE);
        theme.textRenderer().end();

        // Render hover tooltip (structure takes priority over waypoint)
        if (hoveredStructure != null && !contextMenuOpen) {
            boolean hasWaypoint = WaypointManager.get().hasWaypointAt(hoveredStructure.x, hoveredStructure.z, selectedDimension);
            String tooltip = hoveredStructure.type.displayName + " [" + hoveredStructure.x + ", " + hoveredStructure.z + "]";
            if (hasWaypoint) {
                tooltip += " (Waypoint exists)";
            }
            theme.textRenderer().begin(1.0);
            double tx = mouseX + 12;
            double ty = mouseY + 12;
            if (tx + 200 > screenWidth) tx = mouseX - 200;
            if (ty + 20 > screenHeight) ty = mouseY - 30;
            theme.textRenderer().render(tooltip, tx, ty, getStructureColor(hoveredStructure.type));
            theme.textRenderer().end();
        } else if (hoveredWaypoint != null && !contextMenuOpen) {
            String tooltip = "Waypoint: " + hoveredWaypoint.name + " [" + hoveredWaypoint.x + ", " + hoveredWaypoint.z + "]";
            theme.textRenderer().begin(1.0);
            double tx = mouseX + 12;
            double ty = mouseY + 12;
            if (tx + 200 > screenWidth) tx = mouseX - 200;
            if (ty + 20 > screenHeight) ty = mouseY - 30;
            theme.textRenderer().render(tooltip, tx, ty, WAYPOINT_MARKER_COLOR);
            theme.textRenderer().end();
        }

        // Render context menu
        if (contextMenuOpen) {
            drawContextMenu();
        }
    }

    private void renderMap(int mouseX, int mouseY, float delta) {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        int startX = (int) Math.floor((offsetX - (screenWidth / 2 / zoom)) / 16);
        int startZ = (int) Math.floor((offsetZ - (screenHeight / 2 / zoom)) / 16);
        int endX = (int) Math.ceil((offsetX + (screenWidth / 2 / zoom)) / 16);
        int endZ = (int) Math.ceil((offsetZ + (screenHeight / 2 / zoom)) / 16);

        Renderer2D r = Renderer2D.TEXTURE;

        for (int cz = startZ; cz <= endZ; cz++) {
            for (int cx = startX; cx <= endX; cx++) {
                ChunkTile tile = MinimapManager.get().getTile(cx, cz);
                if (tile.texture != null) {
                    double x = (cx * 16 - offsetX) * zoom + screenWidth / 2;
                    double y = (cz * 16 - offsetZ) * zoom + screenHeight / 2;
                    double size = 16 * zoom;

                    r.begin();
                    r.texQuad(x, y, size, size, Color.WHITE);
                    r.render(tile.texture.getTextureView(), tile.texture.getSampler());
                    r.end();
                }
            }
        }

        // Draw chunk grid lines
        r.begin();
        for (int cz = startZ; cz <= endZ; cz++) {
            for (int cx = startX; cx <= endX; cx++) {
                double x = (cx * 16 - offsetX) * zoom + screenWidth / 2;
                double y = (cz * 16 - offsetZ) * zoom + screenHeight / 2;
                double size = 16 * zoom;

                r.boxLines(x, y, size, size, new Color(255, 255, 255, 40));
            }
        }
        r.render();
        r.end();
    }

    private void updateVisibleStructures() {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        int startX = (int) Math.floor((offsetX - (screenWidth / 2 / zoom)) / 16);
        int startZ = (int) Math.floor((offsetZ - (screenHeight / 2 / zoom)) / 16);
        int endX = (int) Math.ceil((offsetX + (screenWidth / 2 / zoom)) / 16);
        int endZ = (int) Math.ceil((offsetZ + (screenHeight / 2 / zoom)) / 16);

        // Add a margin of 10 chunks to pre-cache neighboring regions
        int margin = 10;
        visibleStructures = StructureCache.get().getStructures(
            startX - margin, startZ - margin,
            endX + margin, endZ + margin,
            selectedDimension
        );
    }

    private void updateVisibleWaypoints() {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        int startChunkX = (int) Math.floor((offsetX - (screenWidth / 2 / zoom)) / 16);
        int startChunkZ = (int) Math.floor((offsetZ - (screenHeight / 2 / zoom)) / 16);
        int endChunkX = (int) Math.ceil((offsetX + (screenWidth / 2 / zoom)) / 16);
        int endChunkZ = (int) Math.ceil((offsetZ + (screenHeight / 2 / zoom)) / 16);

        // Add margin
        int margin = 10;
        int blockMinX = (startChunkX - margin) * 16;
        int blockMinZ = (startChunkZ - margin) * 16;
        int blockMaxX = (endChunkX + margin) * 16;
        int blockMaxZ = (endChunkZ + margin) * 16;

        visibleWaypoints.clear();
        for (SeedWaypoint sw : WaypointManager.get().getSeedWaypoints(selectedDimension)) {
            if (sw.x >= blockMinX && sw.x <= blockMaxX && sw.z >= blockMinZ && sw.z <= blockMaxZ) {
                visibleWaypoints.add(sw);
            }
        }
    }

    private void renderStructures(int mouseX, int mouseY) {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        hoveredStructure = null;
        double hoverThreshold = 8 / zoom; // Adjusted for zoom level

        for (GeneratedStructure gs : visibleStructures) {
            double sx = (gs.x - offsetX) * zoom + screenWidth / 2;
            double sy = (gs.z - offsetZ) * zoom + screenHeight / 2;

            // Skip if outside visible area
            if (sx < -20 || sx > screenWidth + 20 || sy < -20 || sy > screenHeight + 20) continue;

            Color color = getStructureColor(gs.type);

            // Dim the color if a waypoint already exists at this location
            if (WaypointManager.get().hasWaypointAt(gs.x, gs.z, selectedDimension)) {
                color = new Color(color.r / 2, color.g / 2, color.b / 2, color.a / 2);
            }

            double iconSize = Math.max(6, 12 * zoom);
            iconSize = Math.min(iconSize, 24); // Cap at large zoom

            Renderer2D r = Renderer2D.COLOR;
            r.begin();

            // Draw structure icon (diamond shape)
            double half = iconSize / 2;
            r.triangle(sx, sy - half, sx - half, sy, sx, sy + half, color);
            r.triangle(sx, sy - half, sx + half, sy, sx, sy + half, color);

            r.render();
            r.end();

            // Check hover
            double dx = mouseX - sx;
            double dy = mouseY - sy;
            double dist = Math.sqrt(dx * dx + dy * dy);
            if (dist < hoverThreshold + iconSize / 2) {
                hoveredStructure = gs;
            }
        }
    }

    private void updateVisibleOres() {
        SeedExplorerModule module = Modules.get().get(SeedExplorerModule.class);
        if (module == null || !module.oreOverlay.get()) {
            visibleOres.clear();
            return;
        }

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        int startX = (int) Math.floor((offsetX - (screenWidth / 2 / zoom)) / 16);
        int startZ = (int) Math.floor((offsetZ - (screenHeight / 2 / zoom)) / 16);
        int endX = (int) Math.ceil((offsetX + (screenWidth / 2 / zoom)) / 16);
        int endZ = (int) Math.ceil((offsetZ + (screenHeight / 2 / zoom)) / 16);

        // Add a margin of 10 chunks to pre-cache neighboring regions
        int margin = 10;
        visibleOres = OreCache.get().getOres(
            startX - margin, startZ - margin,
            endX + margin, endZ + margin,
            selectedDimension
        );
    }

    private void renderOres(int mouseX, int mouseY) {
        SeedExplorerModule module = Modules.get().get(SeedExplorerModule.class);
        if (module == null || !module.oreOverlay.get() || visibleOres.isEmpty()) return;

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        Renderer2D r = Renderer2D.COLOR;
        r.begin();

        for (OrePatch patch : visibleOres) {
            double sx = (patch.x - offsetX) * zoom + screenWidth / 2;
            double sy = (patch.z - offsetZ) * zoom + screenHeight / 2;

            // Skip if outside visible area
            if (sx < -20 || sx > screenWidth + 20 || sy < -20 || sy > screenHeight + 20) continue;

            Color color = patch.type.color;
            double dotSize = Math.max(3, 6 * zoom);
            dotSize = Math.min(dotSize, 12);

            double half = dotSize / 2;
            r.quad(sx - half, sy - half, dotSize, dotSize, color);
        }

        r.render();
        r.end();
    }

    private void renderWaypoints(int mouseX, int mouseY) {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        hoveredWaypoint = null;
        double hoverThreshold = 8 / zoom;

        for (SeedWaypoint sw : visibleWaypoints) {
            double sx = (sw.x - offsetX) * zoom + screenWidth / 2;
            double sy = (sw.z - offsetZ) * zoom + screenHeight / 2;

            // Skip if outside visible area
            if (sx < -20 || sx > screenWidth + 20 || sy < -20 || sy > screenHeight + 20) continue;

            // Check if there's a structure at this position that's being hovered
            boolean skip = false;
            if (hoveredStructure != null) {
                double structSx = (hoveredStructure.x - offsetX) * zoom + screenWidth / 2;
                double structSy = (hoveredStructure.z - offsetZ) * zoom + screenHeight / 2;
                double dist = Math.sqrt(Math.pow(sx - structSx, 2) + Math.pow(sy - structSy, 2));
                if (dist < 10) {
                    skip = true;
                }
            }
            if (skip) continue;

            Color color = WAYPOINT_MARKER_COLOR;
            double iconSize = Math.max(6, 12 * zoom);
            iconSize = Math.min(iconSize, 24);

            // Check hover for waypoint
            double dx = mouseX - sx;
            double dy = mouseY - sy;
            double dist = Math.sqrt(dx * dx + dy * dy);
            boolean hovering = dist < hoverThreshold + iconSize / 2;

            if (hovering) {
                color = WAYPOINT_HOVER_COLOR;
                hoveredWaypoint = sw;
            }

            Renderer2D r = Renderer2D.COLOR;
            r.begin();

            // Draw waypoint marker (square with border)
            double half = iconSize / 2;
            r.quad(sx - half, sy - half, iconSize, iconSize, color);
            // Inner cross
            r.quad(sx - half + 2, sy - 1, iconSize - 4, 2, new Color(40, 40, 40, 180));
            r.quad(sx - 1, sy - half + 2, 2, iconSize - 4, new Color(40, 40, 40, 180));

            r.render();
            r.end();
        }
    }

    private Color getStructureColor(StructureType type) {
        return switch (type) {
            case VILLAGE -> VILLAGE_COLOR;
            case DESERT_PYRAMID -> DESERT_COLOR;
            case JUNGLE_TEMPLE -> JUNGLE_COLOR;
            case WITCH_HUT -> WITCH_COLOR;
            case IGLOO -> IGLOO_COLOR;
            case OUTPOST -> OUTPOST_COLOR;
            case MONUMENT -> MONUMENT_COLOR;
            case MANSION -> MANSION_COLOR;
            case ANCIENT_CITY -> ANCIENT_CITY_COLOR;
            case RUINED_PORTAL -> PORTAL_COLOR;
            case SHIPWRECK -> SHIPWRECK_COLOR;
            case OCEAN_RUIN -> RUIN_COLOR;
            case TREASURE -> TREASURE_COLOR;
            case FORTRESS -> FORTRESS_COLOR;
            case BASTION -> BASTION_COLOR;
            case END_CITY -> END_CITY_COLOR;
        };
    }

    private void drawDimensionSelector() {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();

        String[] dimNames = {"Overworld", "Nether", "End"};
        int[] dimValues = {0, -1, 1};
        int btnWidth = 80;
        int btnHeight = 20;
        int startX = 10;
        int startY = 10;

        // Draw waypoint count indicator
        int wpCount = WaypointManager.get().getSeedWaypoints(selectedDimension).size();
        String wpLabel = "WP: " + wpCount;
        int wpLabelX = startX + 3 * (btnWidth + 4);

        for (int i = 0; i < dimNames.length; i++) {
            int x = startX + i * (btnWidth + 4);
            boolean selected = selectedDimension == dimValues[i];

            Color bgColor = selected ? new Color(80, 120, 200, 200) : new Color(40, 40, 40, 180);
            Color textColor = selected ? Color.WHITE : new Color(180, 180, 180);

            Renderer2D r = Renderer2D.COLOR;
            r.begin();
            r.quad(x, startY, btnWidth, btnHeight, bgColor);
            r.render();
            r.end();

            theme.textRenderer().begin(1.0);
            theme.textRenderer().render(dimNames[i], x + 8, startY + 4, textColor);
            theme.textRenderer().end();
        }

        // Draw waypoint count
        theme.textRenderer().begin(1.0);
        theme.textRenderer().render(wpLabel, wpLabelX, startY + 4, WAYPOINT_MARKER_COLOR);
        theme.textRenderer().end();
    }

    private void drawContextMenu() {
        String[] items;
        int itemHeight = 20;
        int menuWidth;

        if (isWaypointContextMenu) {
            items = new String[]{"Copy Coords", "Delete Waypoint", "Center Map"};
            menuWidth = 160;
        } else {
            boolean hasWaypoint = selectedStructure != null && WaypointManager.get().hasWaypointAt(
                selectedStructure.x, selectedStructure.z, selectedDimension);
            if (hasWaypoint) {
                items = new String[]{"Copy Coords", "Waypoint Exists", "Center Map"};
            } else {
                items = new String[]{"Copy Coords", "Create Waypoint", "Center Map"};
            }
            menuWidth = 160;
        }

        int menuHeight = items.length * itemHeight;

        // Clamp to screen
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        double mx = Math.min(contextMenuX, screenWidth - menuWidth);
        double my = Math.min(contextMenuY, screenHeight - menuHeight);
        if (mx < 0) mx = 0;
        if (my < 0) my = 0;

        // Background
        Renderer2D r = Renderer2D.COLOR;
        r.begin();
        r.quad(mx, my, menuWidth, menuHeight, new Color(20, 20, 30, 230));
        r.render();
        r.end();

        // Items
        theme.textRenderer().begin(1.0);
        for (int i = 0; i < items.length; i++) {
            double iy = my + i * itemHeight;
            Color itemColor = new Color(200, 200, 200);
            // Dim the middle item if it's disabled
            if (!isWaypointContextMenu && i == 1 && selectedStructure != null &&
                WaypointManager.get().hasWaypointAt(selectedStructure.x, selectedStructure.z, selectedDimension)) {
                itemColor = new Color(120, 120, 120);
            }
            theme.textRenderer().render(items[i], mx + 8, iy + 4, itemColor);
        }
        theme.textRenderer().end();

        // Item dividers
        r.begin();
        for (int i = 1; i < items.length; i++) {
            double iy = my + i * itemHeight;
            r.quad(mx, iy, menuWidth, 1, new Color(60, 60, 80, 200));
        }
        r.render();
        r.end();
    }

    private void handleContextMenuClick(double mouseX, double mouseY) {
        int itemHeight = 20;
        int menuWidth = 160;

        String[] items;
        if (isWaypointContextMenu) {
            items = new String[]{"Copy Coords", "Delete Waypoint", "Center Map"};
        } else {
            items = new String[]{"Copy Coords", "Create Waypoint", "Center Map"};
        }
        int menuHeight = items.length * itemHeight;

        double mx = Math.min(contextMenuX, Minecraft.getInstance().getWindow().getGuiScaledWidth() - menuWidth);
        double my = Math.min(contextMenuY, Minecraft.getInstance().getWindow().getGuiScaledHeight() - menuHeight);
        if (mx < 0) mx = 0;
        if (my < 0) my = 0;

        int clickedIndex = -1;
        for (int i = 0; i < items.length; i++) {
            double ix = mx;
            double iy = my + i * itemHeight;
            if (mouseX >= ix && mouseX <= ix + menuWidth && mouseY >= iy && mouseY <= iy + itemHeight) {
                clickedIndex = i;
                break;
            }
        }

        if (clickedIndex >= 0) {
            if (isWaypointContextMenu) {
                handleWaypointContextAction(clickedIndex);
            } else {
                handleStructureContextAction(clickedIndex);
            }
        }

        contextMenuOpen = false;
        selectedStructure = null;
        selectedWaypoint = null;
    }

    private void handleWaypointContextAction(int index) {
        if (selectedWaypoint == null) return;

        switch (index) {
            case 0 -> copyCoords(selectedWaypoint.x, selectedWaypoint.z);
            case 1 -> {
                WaypointManager.get().removeWaypoint(selectedWaypoint);
                visibleWaypoints.remove(selectedWaypoint);
            }
            case 2 -> centerMap(selectedWaypoint.x, selectedWaypoint.z);
        }
    }

    private void handleStructureContextAction(int index) {
        if (selectedStructure == null) return;

        switch (index) {
            case 0 -> copyCoords(selectedStructure.x, selectedStructure.z);
            case 1 -> {
                if (!WaypointManager.get().hasWaypointAt(selectedStructure.x, selectedStructure.z, selectedDimension)) {
                    createWaypoint(selectedStructure);
                }
            }
            case 2 -> centerMap(selectedStructure.x, selectedStructure.z);
        }
    }

    private void copyCoords(int x, int z) {
        String coords = x + ", " + z;
        Minecraft.getInstance().keyboardHandler.setClipboard(coords);
    }

    private void createWaypoint(GeneratedStructure gs) {
        String name = gs.type.displayName + " [" + gs.x + ", " + gs.z + "]";
        String icon = switch (gs.type) {
            case VILLAGE -> "square";
            case DESERT_PYRAMID, JUNGLE_TEMPLE, WITCH_HUT, IGLOO -> "triangle";
            case OUTPOST -> "skull";
            case MONUMENT, MANSION -> "diamond";
            case ANCIENT_CITY -> "star";
            case FORTRESS, BASTION -> "skull";
            case END_CITY -> "star";
            default -> "circle";
        };
        String structureType = gs.type.displayName;
        WaypointManager.get().createWaypoint(name, gs.x, gs.z, selectedDimension, icon, structureType);
    }

    private void centerMap(int x, int z) {
        offsetX = x;
        offsetZ = z;
    }

    // ---- Search functionality ----

    private void onSearch() {
        if (searchBar == null) return;
        String query = searchBar.get().trim();
        if (query.isEmpty()) return;

        // Try coordinate search first
        if (tryCoordinateSearch(query)) return;

        // Try structure search
        if (tryStructureSearch(query)) return;

        // Try biome search
        if (tryBiomeSearch(query)) return;

        // No results found
        ChatUtils.info("Seed Explorer: No results found for \"(highlight)" + query + "(default)\".");
    }

    private boolean tryCoordinateSearch(String query) {
        // Try parsing "X Z" format
        String[] parts = query.split("\\s+");
        if (parts.length == 2) {
            try {
                int x = Integer.parseInt(parts[0]);
                int z = Integer.parseInt(parts[1]);
                centerMap(x, z);
                ChatUtils.info("Seed Explorer: Centered on coordinates (highlight)" + x + ", " + z + "(default).");
                return true;
            } catch (NumberFormatException ignored) {
            }
        }
        return false;
    }

    private boolean tryStructureSearch(String query) {
        StructureType matchedType = null;
        for (StructureType type : StructureType.values()) {
            if (type.displayName.equalsIgnoreCase(query)) {
                matchedType = type;
                break;
            }
        }
        if (matchedType == null) return false;

        // Check if this structure type is valid for the current dimension
        if (matchedType.dimension != selectedDimension) {
            ChatUtils.info("Seed Explorer: \"(highlight)" + matchedType.displayName + "(default)\" does not generate in the current dimension.");
            return false;
        }

        long seed = SeedManager.get().getWorldSeed();
        if (seed == 0) {
            ChatUtils.info("Seed Explorer: No seed set.");
            return false;
        }
        long s48 = seed & ((1L << 48) - 1);

        // Start from current view center and search expanding regions
        int centerBlockX = (int) offsetX;
        int centerBlockZ = (int) offsetZ;

        int originRegionX = Math.floorDiv(centerBlockX, matchedType.regionSize * 16);
        int originRegionZ = Math.floorDiv(centerBlockZ, matchedType.regionSize * 16);

        int searchRadius = 20; // Search 20 regions in each direction

        GeneratedStructure closest = null;
        double closestDist = Double.MAX_VALUE;

        for (int dr = 0; dr <= searchRadius; dr++) {
            for (int rz = -dr; rz <= dr; rz++) {
                for (int rx = -dr; rx <= dr; rx++) {
                    if (Math.abs(rx) != dr && Math.abs(rz) != dr) continue;

                    int regX = originRegionX + rx;
                    int regZ = originRegionZ + rz;

                    GeneratedStructure gs = StructurePredictor.predictInRegionRaw(matchedType, s48, regX, regZ);
                    if (gs != null) {
                        double dx = gs.x - centerBlockX;
                        double dz = gs.z - centerBlockZ;
                        double dist = dx * dx + dz * dz;
                        if (dist < closestDist) {
                            closestDist = dist;
                            closest = gs;
                        }
                    }
                }
            }
            // If we found something at this radius, stop expanding
            if (closest != null) break;
        }

        if (closest != null) {
            centerMap(closest.x, closest.z);
            ChatUtils.info("Seed Explorer: Found (highlight)" + matchedType.displayName + "(default) at (highlight)" + closest.x + ", " + closest.z + "(default).");
            return true;
        }

        ChatUtils.info("Seed Explorer: No (highlight)" + matchedType.displayName + "(default) found within search range.");
        return false;
    }

    private boolean tryBiomeSearch(String query) {
        // Match query against biome name map (case-insensitive)
        String lowerQuery = query.toLowerCase();
        Integer biomeId = null;

        // Try exact match first
        if (BIOME_NAME_TO_ID.containsKey(lowerQuery)) {
            biomeId = BIOME_NAME_TO_ID.get(lowerQuery);
        } else {
            // Try partial match
            for (Map.Entry<String, Integer> entry : BIOME_NAME_TO_ID.entrySet()) {
                if (entry.getKey().contains(lowerQuery)) {
                    biomeId = entry.getValue();
                    break;
                }
            }
        }

        if (biomeId == null) return false;

        long seed = SeedManager.get().getWorldSeed();
        if (seed == 0) {
            ChatUtils.info("Seed Explorer: No seed set.");
            return false;
        }

        int centerBlockX = (int) offsetX;
        int centerBlockZ = (int) offsetZ;

        // Search in expanding squares with step of 16 blocks (1 chunk)
        int maxRadius = 10000; // Max search radius in blocks
        int step = 16; // Check every chunk

        for (int radius = 0; radius <= maxRadius; radius += step) {
            // Search the perimeter of the current radius
            // Top and bottom edges
            for (int bx = -radius; bx <= radius; bx += step) {
                if (radius == 0) {
                    int id = BiomeGenerator.getBiome(centerBlockX, centerBlockZ, seed);
                    if (id == biomeId) {
                        centerMap(centerBlockX, centerBlockZ);
                        ChatUtils.info("Seed Explorer: Found biome at (highlight)" + centerBlockX + ", " + centerBlockZ + "(default).");
                        return true;
                    }
                    continue;
                }

                // Top edge: z = -radius
                int idTop = BiomeGenerator.getBiome(centerBlockX + bx, centerBlockZ - radius, seed);
                if (idTop == biomeId) {
                    centerMap(centerBlockX + bx, centerBlockZ - radius);
                    ChatUtils.info("Seed Explorer: Found biome at (highlight)" + (centerBlockX + bx) + ", " + (centerBlockZ - radius) + "(default).");
                    return true;
                }

                // Bottom edge: z = radius
                int idBottom = BiomeGenerator.getBiome(centerBlockX + bx, centerBlockZ + radius, seed);
                if (idBottom == biomeId) {
                    centerMap(centerBlockX + bx, centerBlockZ + radius);
                    ChatUtils.info("Seed Explorer: Found biome at (highlight)" + (centerBlockX + bx) + ", " + (centerBlockZ + radius) + "(default).");
                    return true;
                }
            }

            // Left and right edges (excluding corners already checked)
            for (int bz = -radius + step; bz <= radius - step; bz += step) {
                // Left edge: x = -radius
                int idLeft = BiomeGenerator.getBiome(centerBlockX - radius, centerBlockZ + bz, seed);
                if (idLeft == biomeId) {
                    centerMap(centerBlockX - radius, centerBlockZ + bz);
                    ChatUtils.info("Seed Explorer: Found biome at (highlight)" + (centerBlockX - radius) + ", " + (centerBlockZ + bz) + "(default).");
                    return true;
                }

                // Right edge: x = radius
                int idRight = BiomeGenerator.getBiome(centerBlockX + radius, centerBlockZ + bz, seed);
                if (idRight == biomeId) {
                    centerMap(centerBlockX + radius, centerBlockZ + bz);
                    ChatUtils.info("Seed Explorer: Found biome at (highlight)" + (centerBlockX + radius) + ", " + (centerBlockZ + bz) + "(default).");
                    return true;
                }
            }
        }

        ChatUtils.info("Seed Explorer: No (highlight)" + query + "(default) biome found within " + maxRadius + " blocks.");
        return false;
    }

    @Override
    public boolean mouseClicked(net.minecraft.client.input.MouseButtonEvent click, boolean doubled) {
        if (contextMenuOpen) {
            handleContextMenuClick(click.x(), click.y());
            return true;
        }

        // Let widgets (e.g. search bar) handle clicks first
        if (super.mouseClicked(click, doubled)) {
            return true;
        }

        if (click.button() == 0) { // LEFT button - pan
            dragging = true;
            dragStartX = click.x();
            dragStartY = click.y();
            dragOffsetX = offsetX;
            dragOffsetZ = offsetZ;
            return true;
        }

        if (click.button() == 1) { // RIGHT button - context menu
            if (hoveredStructure != null) {
                selectedStructure = hoveredStructure;
                selectedWaypoint = null;
                isWaypointContextMenu = false;
                contextMenuOpen = true;
                contextMenuX = click.x();
                contextMenuY = click.y();
                return true;
            }
            if (hoveredWaypoint != null) {
                selectedWaypoint = hoveredWaypoint;
                selectedStructure = null;
                isWaypointContextMenu = true;
                contextMenuOpen = true;
                contextMenuX = click.x();
                contextMenuY = click.y();
                return true;
            }
        }

        // Handle dimension selector clicks
        if (click.button() == 0) {
            double clickX = click.x();
            double clickY = click.y();
            if (clickY >= 10 && clickY <= 30) {
                int[] dimValues = {0, -1, 1};
                int btnWidth = 80;
                int startX = 10;
                for (int i = 0; i < dimValues.length; i++) {
                    int bx = startX + i * (btnWidth + 4);
                    if (clickX >= bx && clickX <= bx + btnWidth) {
                        if (selectedDimension != dimValues[i]) {
                            selectedDimension = dimValues[i];
                            StructureCache.get().clear();
                            OreCache.get().clear();
                        }
                        return true;
                    }
                }
            }
        }

        return false;
    }

    @Override
    public boolean mouseReleased(net.minecraft.client.input.MouseButtonEvent click) {
        if (click.button() == 0) {
            dragging = false;
            return true;
        }
        return super.mouseReleased(click);
    }

    @Override
    public void mouseMoved(double mouseX, double mouseY) {
        super.mouseMoved(mouseX, mouseY);

        if (dragging) {
            double dx = mouseX - dragStartX;
            double dy = mouseY - dragStartY;
            double scale = Minecraft.getInstance().getWindow().getGuiScale();
            offsetX = dragOffsetX - (dx / scale) / zoom;
            offsetZ = dragOffsetZ - (dy / scale) / zoom;
        }
    }

    @Override
    public boolean mouseScrolled(double mouseX, double mouseY, double horizontalAmount, double verticalAmount) {
        double zoomStep = 1.2;
        double oldZoom = zoom;
        if (verticalAmount > 0) zoom *= zoomStep;
        else zoom /= zoomStep;
        zoom = Mth.clamp(zoom, 0.01, 100.0);

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        // Adjust offset so we zoom into the mouse position
        offsetX += (mouseX - screenWidth / 2.0) / oldZoom - (mouseX - screenWidth / 2.0) / zoom;
        offsetZ += (mouseY - screenHeight / 2.0) / oldZoom - (mouseY - screenHeight / 2.0) / zoom;

        return true;
    }

    @Override
    public boolean keyPressed(net.minecraft.client.input.KeyEvent key) {
        if (contextMenuOpen) {
            contextMenuOpen = false;
            selectedStructure = null;
            selectedWaypoint = null;
            return true;
        }

        // Let widgets (e.g. search bar) handle keys first
        if (super.keyPressed(key)) {
            return true;
        }

        return false;
    }
}