/*
 * This file is part of the Meteor Seed Explorer Addon distribution (https://github.com/SeedExplorer/meteor-seed-explorer).
 * Copyright (c) SeedExplorer Team.
 */

package me.seedexplorer.addon.gui;

import me.seedexplorer.addon.map.ChunkTile;
import me.seedexplorer.addon.map.MinimapManager;
import meteordevelopment.meteorclient.gui.GuiTheme;
import meteordevelopment.meteorclient.gui.WidgetScreen;
import meteordevelopment.meteorclient.renderer.Renderer2D;
import meteordevelopment.meteorclient.utils.render.color.Color;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.util.Mth;

/**
 * Fullscreen infinite map screen for seed exploration.
 * Supports panning with left-click drag and zooming with scroll wheel.
 * Renders chunk tiles generated by MinimapManager using BiomeGenerator.
 */
public class SeedExplorerScreen extends WidgetScreen {
    private double offsetX, offsetZ;
    private double zoom = 1.0;

    private boolean dragging;
    private double dragStartX, dragStartY;
    private double dragOffsetX, dragOffsetZ;

    public SeedExplorerScreen(GuiTheme theme) {
        super(theme, "Seed Explorer");
    }

    @Override
    public void initWidgets() {
    }

    @Override
    protected void onRenderBefore(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
        // Render the map
        renderMap(mouseX, mouseY, delta);

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        // Draw coordinates overlay at bottom-left
        double worldX = offsetX + (mouseX - screenWidth / 2.0) / zoom;
        double worldZ = offsetZ + (mouseY - screenHeight / 2.0) / zoom;
        String coords = String.format("X: %.1f, Z: %.1f (Zoom: %.2f)", worldX, worldZ, zoom);
        theme.textRenderer().begin(1.0);
        theme.textRenderer().render(coords, 10, screenHeight - 20, theme.textColor());
        theme.textRenderer().end();

        // Draw crosshair at center
        double cx = screenWidth / 2.0;
        double cy = screenHeight / 2.0;
        theme.textRenderer().begin(1.0);
        theme.textRenderer().render("+", cx - 3, cy - 4, Color.WHITE);
        theme.textRenderer().end();
    }

    private void renderMap(int mouseX, int mouseY, float delta) {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        // Calculate visible chunk range based on current offset and zoom
        int startX = (int) Math.floor((offsetX - (screenWidth / 2 / zoom)) / 16);
        int startZ = (int) Math.floor((offsetZ - (screenHeight / 2 / zoom)) / 16);
        int endX = (int) Math.ceil((offsetX + (screenWidth / 2 / zoom)) / 16);
        int endZ = (int) Math.ceil((offsetZ + (screenHeight / 2 / zoom)) / 16);

        Renderer2D r = Renderer2D.TEXTURE;

        // Render each chunk tile with its own begin/render/end cycle since
        // each tile has a unique GPU texture
        for (int cz = startZ; cz <= endZ; cz++) {
            for (int cx = startX; cx <= endX; cx++) {
                ChunkTile tile = MinimapManager.get().getTile(cx, cz);
                if (tile.texture != null) {
                    double x = (cx * 16 - offsetX) * zoom + screenWidth / 2;
                    double y = (cz * 16 - offsetZ) * zoom + screenHeight / 2;
                    double size = 16 * zoom;

                    r.begin();
                    r.texQuad(x, y, size, size, Color.WHITE);
                    r.render(tile.texture.getTextureView(), tile.texture.getSampler());
                    r.end();
                }
            }
        }

        // Draw chunk grid lines as overlay
        r.begin();
        for (int cz = startZ; cz <= endZ; cz++) {
            for (int cx = startX; cx <= endX; cx++) {
                double x = (cx * 16 - offsetX) * zoom + screenWidth / 2;
                double y = (cz * 16 - offsetZ) * zoom + screenHeight / 2;
                double size = 16 * zoom;

                r.boxLines(x, y, size, size, new Color(255, 255, 255, 40));
            }
        }
        r.render();
        r.end();
    }

    @Override
    public boolean mouseClicked(net.minecraft.client.input.MouseButtonEvent click, boolean doubled) {
        if (click.button() == 0) { // LEFT button
            dragging = true;
            dragStartX = click.x();
            dragStartY = click.y();
            dragOffsetX = offsetX;
            dragOffsetZ = offsetZ;
            return true;
        }
        return super.mouseClicked(click, doubled);
    }

    @Override
    public boolean mouseReleased(net.minecraft.client.input.MouseButtonEvent click) {
        if (click.button() == 0) {
            dragging = false;
            return true;
        }
        return super.mouseReleased(click);
    }

    @Override
    public void mouseMoved(double mouseX, double mouseY) {
        super.mouseMoved(mouseX, mouseY);

        if (dragging) {
            double dx = mouseX - dragStartX;
            double dy = mouseY - dragStartY;
            // Account for GUI scale
            double scale = Minecraft.getInstance().getWindow().getGuiScale();
            offsetX = dragOffsetX - (dx / scale) / zoom;
            offsetZ = dragOffsetZ - (dy / scale) / zoom;
        }
    }

    @Override
    public boolean mouseScrolled(double mouseX, double mouseY, double horizontalAmount, double verticalAmount) {
        double zoomStep = 1.2;
        double oldZoom = zoom;
        if (verticalAmount > 0) zoom *= zoomStep;
        else zoom /= zoomStep;
        zoom = Mth.clamp(zoom, 0.01, 100.0);

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        // Adjust offset so we zoom into the mouse position
        offsetX += (mouseX - screenWidth / 2.0) / oldZoom - (mouseX - screenWidth / 2.0) / zoom;
        offsetZ += (mouseY - screenHeight / 2.0) / oldZoom - (mouseY - screenHeight / 2.0) / zoom;

        return true;
    }
}