/*
 * This file is part of the Meteor Seed Explorer Addon distribution (https://github.com/SeedExplorer/meteor-seed-explorer).
 * Copyright (c) SeedExplorer Team.
 */

package me.seedexplorer.addon.gui;

import me.seedexplorer.addon.map.ChunkTile;
import me.seedexplorer.addon.map.MinimapManager;
import me.seedexplorer.addon.structures.GeneratedStructure;
import me.seedexplorer.addon.structures.StructureCache;
import me.seedexplorer.addon.structures.StructureType;
import me.seedexplorer.addon.waypoints.WaypointManager;
import meteordevelopment.meteorclient.gui.GuiTheme;
import meteordevelopment.meteorclient.gui.WidgetScreen;
import meteordevelopment.meteorclient.gui.renderer.GuiRenderer;
import meteordevelopment.meteorclient.renderer.Renderer2D;
import meteordevelopment.meteorclient.utils.render.color.Color;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.util.Mth;

import java.util.ArrayList;
import java.util.List;

/**
 * Fullscreen infinite map screen for seed exploration.
 * Supports panning with left-click drag and zooming with scroll wheel.
 * Renders chunk tiles generated by MinimapManager using BiomeGenerator.
 * Renders predicted structure icons as a layer on top of the biome map.
 * Provides hover tooltips and right-click context menu for structures.
 */
public class SeedExplorerScreen extends WidgetScreen {
    private double offsetX, offsetZ;
    private double zoom = 1.0;

    private boolean dragging;
    private double dragStartX, dragStartY;
    private double dragOffsetX, dragOffsetZ;

    // Dimension selector
    private int selectedDimension = 0; // 0=Overworld, -1=Nether, 1=End

    // Structure data
    private List<GeneratedStructure> visibleStructures = new ArrayList<>();
    private GeneratedStructure hoveredStructure;
    private GeneratedStructure selectedStructure;

    // Context menu
    private boolean contextMenuOpen;
    private double contextMenuX, contextMenuY;

    // Structure icon colors by type
    private static final Color VILLAGE_COLOR = new Color(180, 60, 60, 220);
    private static final Color DESERT_COLOR = new Color(220, 200, 80, 220);
    private static final Color JUNGLE_COLOR = new Color(60, 200, 60, 220);
    private static final Color WITCH_COLOR = new Color(120, 40, 160, 220);
    private static final Color IGLOO_COLOR = new Color(200, 220, 240, 220);
    private static final Color OUTPOST_COLOR = new Color(120, 120, 120, 220);
    private static final Color MONUMENT_COLOR = new Color(40, 100, 220, 220);
    private static final Color MANSION_COLOR = new Color(160, 80, 40, 220);
    private static final Color ANCIENT_CITY_COLOR = new Color(40, 200, 180, 220);
    private static final Color PORTAL_COLOR = new Color(180, 40, 200, 220);
    private static final Color SHIPWRECK_COLOR = new Color(160, 120, 60, 220);
    private static final Color RUIN_COLOR = new Color(100, 140, 180, 220);
    private static final Color TREASURE_COLOR = new Color(255, 215, 0, 220);
    private static final Color FORTRESS_COLOR = new Color(180, 40, 40, 220);
    private static final Color BASTION_COLOR = new Color(120, 60, 140, 220);
    private static final Color END_CITY_COLOR = new Color(160, 60, 200, 220);

    public SeedExplorerScreen(GuiTheme theme) {
        super(theme, "Seed Explorer");
    }

    @Override
    public void initWidgets() {
    }

    @Override
    protected void onRenderBefore(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
        renderMap(mouseX, mouseY, delta);

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        // Update visible structures based on current viewport
        updateVisibleStructures();

        // Render structure icons
        renderStructures(mouseX, mouseY);

        // Draw coordinates overlay at bottom-left
        double worldX = offsetX + (mouseX - screenWidth / 2.0) / zoom;
        double worldZ = offsetZ + (mouseY - screenHeight / 2.0) / zoom;
        String coords = String.format("X: %.1f, Z: %.1f (Zoom: %.2f)", worldX, worldZ, zoom);
        theme.textRenderer().begin(1.0);
        theme.textRenderer().render(coords, 10, screenHeight - 20, theme.textColor());
        theme.textRenderer().end();

        // Draw dimension selector at top-left
        drawDimensionSelector();

        // Draw crosshair at center
        double cx = screenWidth / 2.0;
        double cy = screenHeight / 2.0;
        theme.textRenderer().begin(1.0);
        theme.textRenderer().render("+", cx - 3, cy - 4, Color.WHITE);
        theme.textRenderer().end();

        // Render hover tooltip
        if (hoveredStructure != null && !contextMenuOpen) {
            String tooltip = hoveredStructure.type.displayName + " [" + hoveredStructure.x + ", " + hoveredStructure.z + "]";
            theme.textRenderer().begin(1.0);
            double tx = mouseX + 12;
            double ty = mouseY + 12;
            if (tx + 200 > screenWidth) tx = mouseX - 200;
            if (ty + 20 > screenHeight) ty = mouseY - 30;
            theme.textRenderer().render(tooltip, tx, ty, getStructureColor(hoveredStructure.type));
            theme.textRenderer().end();
        }

        // Render context menu
        if (contextMenuOpen) {
            drawContextMenu();
        }
    }

    private void renderMap(int mouseX, int mouseY, float delta) {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        int startX = (int) Math.floor((offsetX - (screenWidth / 2 / zoom)) / 16);
        int startZ = (int) Math.floor((offsetZ - (screenHeight / 2 / zoom)) / 16);
        int endX = (int) Math.ceil((offsetX + (screenWidth / 2 / zoom)) / 16);
        int endZ = (int) Math.ceil((offsetZ + (screenHeight / 2 / zoom)) / 16);

        Renderer2D r = Renderer2D.TEXTURE;

        for (int cz = startZ; cz <= endZ; cz++) {
            for (int cx = startX; cx <= endX; cx++) {
                ChunkTile tile = MinimapManager.get().getTile(cx, cz);
                if (tile.texture != null) {
                    double x = (cx * 16 - offsetX) * zoom + screenWidth / 2;
                    double y = (cz * 16 - offsetZ) * zoom + screenHeight / 2;
                    double size = 16 * zoom;

                    r.begin();
                    r.texQuad(x, y, size, size, Color.WHITE);
                    r.render(tile.texture.getTextureView(), tile.texture.getSampler());
                    r.end();
                }
            }
        }

        // Draw chunk grid lines
        r.begin();
        for (int cz = startZ; cz <= endZ; cz++) {
            for (int cx = startX; cx <= endX; cx++) {
                double x = (cx * 16 - offsetX) * zoom + screenWidth / 2;
                double y = (cz * 16 - offsetZ) * zoom + screenHeight / 2;
                double size = 16 * zoom;

                r.boxLines(x, y, size, size, new Color(255, 255, 255, 40));
            }
        }
        r.render();
        r.end();
    }

    private void updateVisibleStructures() {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        int startX = (int) Math.floor((offsetX - (screenWidth / 2 / zoom)) / 16);
        int startZ = (int) Math.floor((offsetZ - (screenHeight / 2 / zoom)) / 16);
        int endX = (int) Math.ceil((offsetX + (screenWidth / 2 / zoom)) / 16);
        int endZ = (int) Math.ceil((offsetZ + (screenHeight / 2 / zoom)) / 16);

        // Add a margin of 10 chunks to pre-cache neighboring regions
        int margin = 10;
        visibleStructures = StructureCache.get().getStructures(
            startX - margin, startZ - margin,
            endX + margin, endZ + margin,
            selectedDimension
        );
    }

    private void renderStructures(int mouseX, int mouseY) {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        hoveredStructure = null;
        double hoverThreshold = 8 / zoom; // Adjusted for zoom level

        for (GeneratedStructure gs : visibleStructures) {
            double sx = (gs.x - offsetX) * zoom + screenWidth / 2;
            double sy = (gs.z - offsetZ) * zoom + screenHeight / 2;

            // Skip if outside visible area
            if (sx < -20 || sx > screenWidth + 20 || sy < -20 || sy > screenHeight + 20) continue;

            Color color = getStructureColor(gs.type);
            double iconSize = Math.max(6, 12 * zoom);
            iconSize = Math.min(iconSize, 24); // Cap at large zoom

            Renderer2D r = Renderer2D.COLOR;
            r.begin();

            // Draw structure icon (diamond shape)
            double half = iconSize / 2;
            r.triangle(sx, sy - half, sx - half, sy, sx, sy + half, color);
            r.triangle(sx, sy - half, sx + half, sy, sx, sy + half, color);

            r.render();
            r.end();

            // Check hover
            double dx = mouseX - sx;
            double dy = mouseY - sy;
            double dist = Math.sqrt(dx * dx + dy * dy);
            if (dist < hoverThreshold + iconSize / 2) {
                hoveredStructure = gs;
            }
        }
    }

    private Color getStructureColor(StructureType type) {
        return switch (type) {
            case VILLAGE -> VILLAGE_COLOR;
            case DESERT_PYRAMID -> DESERT_COLOR;
            case JUNGLE_TEMPLE -> JUNGLE_COLOR;
            case WITCH_HUT -> WITCH_COLOR;
            case IGLOO -> IGLOO_COLOR;
            case OUTPOST -> OUTPOST_COLOR;
            case MONUMENT -> MONUMENT_COLOR;
            case MANSION -> MANSION_COLOR;
            case ANCIENT_CITY -> ANCIENT_CITY_COLOR;
            case RUINED_PORTAL -> PORTAL_COLOR;
            case SHIPWRECK -> SHIPWRECK_COLOR;
            case OCEAN_RUIN -> RUIN_COLOR;
            case TREASURE -> TREASURE_COLOR;
            case FORTRESS -> FORTRESS_COLOR;
            case BASTION -> BASTION_COLOR;
            case END_CITY -> END_CITY_COLOR;
        };
    }

    private void drawDimensionSelector() {
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();

        String[] dimNames = {"Overworld", "Nether", "End"};
        int[] dimValues = {0, -1, 1};
        int btnWidth = 80;
        int btnHeight = 20;
        int startX = 10;
        int startY = 10;

        for (int i = 0; i < dimNames.length; i++) {
            int x = startX + i * (btnWidth + 4);
            boolean selected = selectedDimension == dimValues[i];

            Color bgColor = selected ? new Color(80, 120, 200, 200) : new Color(40, 40, 40, 180);
            Color textColor = selected ? Color.WHITE : new Color(180, 180, 180);

            Renderer2D r = Renderer2D.COLOR;
            r.begin();
            r.quad(x, startY, btnWidth, btnHeight, bgColor);
            r.render();
            r.end();

            theme.textRenderer().begin(1.0);
            theme.textRenderer().render(dimNames[i], x + 8, startY + 4, textColor);
            theme.textRenderer().end();
        }
    }

    private void drawContextMenu() {
        String[] items = {"Copy Coords", "Create Waypoint", "Center Map"};
        int itemHeight = 20;
        int menuWidth = 150;
        int menuHeight = items.length * itemHeight;

        // Clamp to screen
        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        double mx = Math.min(contextMenuX, screenWidth - menuWidth);
        double my = Math.min(contextMenuY, screenHeight - menuHeight);
        if (mx < 0) mx = 0;
        if (my < 0) my = 0;

        // Background
        Renderer2D r = Renderer2D.COLOR;
        r.begin();
        r.quad(mx, my, menuWidth, menuHeight, new Color(20, 20, 30, 230));
        r.render();
        r.end();

        // Items
        theme.textRenderer().begin(1.0);
        for (int i = 0; i < items.length; i++) {
            double iy = my + i * itemHeight;
            Color itemColor = new Color(200, 200, 200);
            theme.textRenderer().render(items[i], mx + 8, iy + 4, itemColor);
        }
        theme.textRenderer().end();

        // Item dividers
        r.begin();
        for (int i = 1; i < items.length; i++) {
            double iy = my + i * itemHeight;
            r.quad(mx, iy, menuWidth, 1, new Color(60, 60, 80, 200));
        }
        r.render();
        r.end();
    }

    private void handleContextMenuClick(double mouseX, double mouseY) {
        if (selectedStructure == null) return;

        String[] items = {"Copy Coords", "Create Waypoint", "Center Map"};
        int itemHeight = 20;
        int menuWidth = 150;

        double mx = Math.min(contextMenuX, Minecraft.getInstance().getWindow().getGuiScaledWidth() - menuWidth);
        double my = Math.min(contextMenuY, Minecraft.getInstance().getWindow().getGuiScaledHeight() - menuHeight);
        if (mx < 0) mx = 0;
        if (my < 0) my = 0;

        int clickedIndex = -1;
        for (int i = 0; i < items.length; i++) {
            double ix = mx;
            double iy = my + i * itemHeight;
            if (mouseX >= ix && mouseX <= ix + menuWidth && mouseY >= iy && mouseY <= iy + itemHeight) {
                clickedIndex = i;
                break;
            }
        }

        if (clickedIndex >= 0) {
            switch (clickedIndex) {
                case 0 -> copyCoords(selectedStructure);
                case 1 -> createWaypoint(selectedStructure);
                case 2 -> centerMap(selectedStructure);
            }
        }

        contextMenuOpen = false;
        selectedStructure = null;
    }

    private void copyCoords(GeneratedStructure gs) {
        String coords = gs.x + ", " + gs.z;
        Minecraft.getInstance().keyboardHandler.setClipboard(coords);
    }

    private void createWaypoint(GeneratedStructure gs) {
        String name = gs.type.displayName + " [" + gs.x + ", " + gs.z + "]";
        String icon = switch (gs.type) {
            case VILLAGE -> "square";
            case DESERT_PYRAMID, JUNGLE_TEMPLE, WITCH_HUT, IGLOO -> "triangle";
            case OUTPOST -> "skull";
            case MONUMENT, MANSION -> "diamond";
            case ANCIENT_CITY -> "star";
            case FORTRESS, BASTION -> "skull";
            case END_CITY -> "star";
            default -> "circle";
        };
        WaypointManager.get().createWaypoint(name, gs.x, gs.z, selectedDimension, icon);
    }

    private void centerMap(GeneratedStructure gs) {
        offsetX = gs.x;
        offsetZ = gs.z;
    }

    @Override
    public boolean mouseClicked(net.minecraft.client.input.MouseButtonEvent click, boolean doubled) {
        if (contextMenuOpen) {
            handleContextMenuClick(click.x(), click.y());
            return true;
        }

        if (click.button() == 0) { // LEFT button - pan
            dragging = true;
            dragStartX = click.x();
            dragStartY = click.y();
            dragOffsetX = offsetX;
            dragOffsetZ = offsetZ;
            return true;
        }

        if (click.button() == 1) { // RIGHT button - context menu
            if (hoveredStructure != null) {
                selectedStructure = hoveredStructure;
                contextMenuOpen = true;
                contextMenuX = click.x();
                contextMenuY = click.y();
                return true;
            }
        }

        // Handle dimension selector clicks
        if (click.button() == 0) {
            double clickX = click.x();
            double clickY = click.y();
            if (clickY >= 10 && clickY <= 30) {
                String[] dimNames = {"Overworld", "Nether", "End"};
                int[] dimValues = {0, -1, 1};
                int btnWidth = 80;
                int startX = 10;
                for (int i = 0; i < dimNames.length; i++) {
                    int bx = startX + i * (btnWidth + 4);
                    if (clickX >= bx && clickX <= bx + btnWidth) {
                        if (selectedDimension != dimValues[i]) {
                            selectedDimension = dimValues[i];
                            StructureCache.get().clear();
                        }
                        return true;
                    }
                }
            }
        }

        return super.mouseClicked(click, doubled);
    }

    @Override
    public boolean mouseReleased(net.minecraft.client.input.MouseButtonEvent click) {
        if (click.button() == 0) {
            dragging = false;
            return true;
        }
        return super.mouseReleased(click);
    }

    @Override
    public void mouseMoved(double mouseX, double mouseY) {
        super.mouseMoved(mouseX, mouseY);

        if (dragging) {
            double dx = mouseX - dragStartX;
            double dy = mouseY - dragStartY;
            double scale = Minecraft.getInstance().getWindow().getGuiScale();
            offsetX = dragOffsetX - (dx / scale) / zoom;
            offsetZ = dragOffsetZ - (dy / scale) / zoom;
        }
    }

    @Override
    public boolean mouseScrolled(double mouseX, double mouseY, double horizontalAmount, double verticalAmount) {
        double zoomStep = 1.2;
        double oldZoom = zoom;
        if (verticalAmount > 0) zoom *= zoomStep;
        else zoom /= zoomStep;
        zoom = Mth.clamp(zoom, 0.01, 100.0);

        Minecraft mc = Minecraft.getInstance();
        double screenWidth = mc.getWindow().getGuiScaledWidth();
        double screenHeight = mc.getWindow().getGuiScaledHeight();

        // Adjust offset so we zoom into the mouse position
        offsetX += (mouseX - screenWidth / 2.0) / oldZoom - (mouseX - screenWidth / 2.0) / zoom;
        offsetZ += (mouseY - screenHeight / 2.0) / oldZoom - (mouseY - screenHeight / 2.0) / zoom;

        return true;
    }

    @Override
    public boolean keyPressed(net.minecraft.client.input.KeyEvent key) {
        if (contextMenuOpen) {
            contextMenuOpen = false;
            selectedStructure = null;
            return true;
        }
        return super.keyPressed(key);
    }
}